
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package FaseCompilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cadena = 13;
  public static final int repetir = 16;
  public static final int decimal = 15;
  public static final int print = 2;
  public static final int llaveabierta = 10;
  public static final int por = 19;
  public static final int pa_close = 9;
  public static final int menos = 18;
  public static final int div = 20;
  public static final int llavecerrada = 11;
  public static final int igual = 7;
  public static final int EOF = 0;
  public static final int id = 12;
  public static final int potencia = 21;
  public static final int tipo_entero = 3;
  public static final int error = 1;
  public static final int pa_open = 8;
  public static final int entero = 14;
  public static final int tipo_doble = 4;
  public static final int umenos = 22;
  public static final int mas = 17;
  public static final int tipo_cadena = 5;
  public static final int puntoycoma = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "print",
  "tipo_entero",
  "tipo_doble",
  "tipo_cadena",
  "puntoycoma",
  "igual",
  "pa_open",
  "pa_close",
  "llaveabierta",
  "llavecerrada",
  "id",
  "cadena",
  "entero",
  "decimal",
  "repetir",
  "mas",
  "menos",
  "por",
  "div",
  "potencia",
  "umenos"
  };
}

